// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DotNetConfDemo
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidDotNetConfDemoPackageString = "13fcac53-9b26-43f9-a72f-bef28ef099a3";
        public static Guid guidDotNetConfDemoPackage = new Guid(guidDotNetConfDemoPackageString);

        public const string guidDotNetConfDemoPackageCmdSetString = "b344cc7d-0d60-4315-9d71-29ef03695fff";
        public static Guid guidDotNetConfDemoPackageCmdSet = new Guid(guidDotNetConfDemoPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int SearchId = 0x0100;
    }
}